# Generated by Django 5.2.2 on 2025-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_balances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_mobi_num', models.CharField(max_length=50, null=True)),
                ('col_cust_no', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='lbt_customer',
            fields=[
                ('col_cust_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('col_firstname', models.CharField(max_length=30)),
                ('col_lastname', models.CharField(max_length=30)),
                ('col_mobi_num', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
