# Generated by Django 5.2.2 on 2025-06-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbt_stuff',
            fields=[
                ('col_stuf_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('col_stuff_firstname', models.CharField(max_length=30)),
                ('col_stuff_lastname', models.CharField(max_length=30)),
                ('col_stuff_mobi_num', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
