# Generated by Django 5.2.2 on 2025-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_lbt_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='account_balances',
            name='col_mobi_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lbt_customer',
            name='col_mobi_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lbt_stuff',
            name='col_stuff_mobi_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
